services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080

  web:
    build: .
    ports:
      - "8000:8000"
    depends_on: 
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://test:password@db:5432/todo

volumes:
  postgres_data: