services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=todo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    image: zeth5/fastapi-todo:latest
    ports:
      - "80:8000"
    depends_on: 
      - db
    environment:
      - DATABASE_URL=postgresql+psycopg2://test:password@db:5432/todo

volumes:
  postgres_data: