name: Docker Image CI

on:
    workflow_run:
        workflows: ['ci']
        types: [completed]
        branches:
            - 'main'
jobs:

  run:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Pull Docker images
      run: docker-compose pull
    - name: Start Docker Compose services
      run: docker-compose up -d
